version: '3.7'

services:
  scottadamsmith-site:
    container_name: scottadamsmith-site
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/node/app/
      - /home/node/.npm
      - /home/node/app/node_modules