version: '3.7'

services:
  scottadamsmith-site:
    container_name: scottadamsmith-site
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces/scottadamsmith-site
      - /home/node/.npm
      - /workspaces/node_modules
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"